"""phase 192 herring pool and drill solve link

Revision ID: 03df30e3c008
Revises: ed0735f3d998
Create Date: 2026-07-27 21:47:35.817268+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03df30e3c008'
down_revision: Union[str, Sequence[str], None] = 'ed0735f3d998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herring_pool',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('ply', sa.SmallInteger(), nullable=False),
    sa.Column('mover_color', sa.String(length=5), nullable=False),
    sa.Column('fen', sa.String(length=120), nullable=False),
    sa.Column('arriving_move_uci', sa.String(length=5), nullable=True),
    sa.Column('phase', sa.SmallInteger(), nullable=False),
    sa.Column('source_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ladder', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(ladder) = 'array' AND jsonb_array_length(ladder) = 5", name='ck_herring_pool_ladder_shape'),
    sa.CheckConstraint("mover_color IN ('white', 'black')", name='ck_herring_pool_mover_color'),
    sa.CheckConstraint('phase IN (0, 1, 2)', name='ck_herring_pool_phase'),
    sa.ForeignKeyConstraint(['game_id', 'user_id'], ['games.id', 'games.user_id'], name='herring_pool_game_user_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'game_id', 'ply', name='uq_herring_pool_source')
    )
    op.create_index('ix_herring_pool_recency', 'herring_pool', ['source_played_at', 'id'], unique=False)
    op.add_column('drill_solves', sa.Column('herring_pool_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        'fk_drill_solves_herring_pool_id', 'drill_solves', 'herring_pool',
        ['herring_pool_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_drill_solves_herring_pool_id', 'drill_solves', type_='foreignkey')
    op.drop_column('drill_solves', 'herring_pool_id')
    op.drop_index('ix_herring_pool_recency', table_name='herring_pool')
    op.drop_table('herring_pool')
    # ### end Alembic commands ###
