"""seed 119 drill solve move quality

Revision ID: ed0735f3d998
Revises: b1724dc27de8
Create Date: 2026-07-27 17:04:16.391341+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0735f3d998'
down_revision: Union[str, Sequence[str], None] = 'b1724dc27de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drill_solves', sa.Column('move_quality', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###
    # Alembic autogenerate does not detect CheckConstraint additions to an
    # existing table, so it is hand-added here (SEED-119).
    op.create_check_constraint(
        'ck_drill_solves_move_quality',
        'drill_solves',
        'move_quality IS NULL OR move_quality IN (0, 1, 2)',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_drill_solves_move_quality', 'drill_solves', type_='check')
    op.drop_column('drill_solves', 'move_quality')
    # ### end Alembic commands ###
