"""phase 189 train tables

Revision ID: 10335efafdb4
Revises: dbf963851fe0
Create Date: 2026-07-25 11:53:48.238823+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "10335efafdb4"
down_revision: Union[str, Sequence[str], None] = "dbf963851fe0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drill_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), server_default="open", nullable=False),
        sa.Column("puzzle_count", sa.SmallInteger(), nullable=False),
        sa.Column("expires_on", sa.Date(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('open', 'completed', 'expired')", name="ck_drill_sessions_status"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_drill_sessions_user_open",
        "drill_sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "train_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("timezone", sa.Text(), server_default="UTC", nullable=False),
        sa.Column("weekday_mask", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("puzzles_per_session", sa.SmallInteger(), server_default="12", nullable=False),
        sa.CheckConstraint(
            "puzzles_per_session BETWEEN 1 AND 50", name="ck_train_settings_puzzles"
        ),
        sa.CheckConstraint("weekday_mask BETWEEN 0 AND 127", name="ck_train_settings_weekday_mask"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "drill_items",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("ply", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("streak", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("fail_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("ever_correct", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("fail_count >= 0", name="ck_drill_items_fail_count"),
        sa.CheckConstraint("status IN (0, 1, 2)", name="ck_drill_items_status"),
        sa.CheckConstraint("streak >= 0", name="ck_drill_items_streak"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "game_id", "ply"),
    )
    op.create_index(
        "ix_drill_items_user_status_due",
        "drill_items",
        ["user_id", "status", "due_date"],
        unique=False,
    )
    op.create_table(
        "drill_solves",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("ply", sa.SmallInteger(), nullable=False),
        sa.Column("source", sa.SmallInteger(), nullable=False),
        sa.Column("guess", sa.SmallInteger(), nullable=True),
        sa.Column("correct_guess", sa.Boolean(), nullable=True),
        sa.Column("correct_move", sa.Boolean(), nullable=True),
        sa.Column("played_move", sa.String(length=5), nullable=True),
        sa.Column("solved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("guess IS NULL OR guess IN (0, 1)", name="ck_drill_solves_guess"),
        sa.CheckConstraint("source IN (0, 1)", name="ck_drill_solves_source"),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["drill_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id", "position"),
        sa.UniqueConstraint("session_id", "game_id", "ply", name="uq_drill_solves_session_puzzle"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drill_solves")
    op.drop_index("ix_drill_items_user_status_due", table_name="drill_items")
    op.drop_table("drill_items")
    op.drop_table("train_settings")
    op.drop_index(
        "uq_drill_sessions_user_open",
        table_name="drill_sessions",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("drill_sessions")
    # ### end Alembic commands ###
